### ISSUE TITLE
COMET Crossview: The crossview element definitions definition and parameter selection panel should allow for filtering of the element definitions based on the category of the element definition

### ISSUE THREAD

**Issue by JVennekens** [RHEAGROUP/COMET-IME-Community-Edition#792] opened 2021-04-09 14:13 UTC
### Prerequisites

- [ ] I have written a descriptive issue title
- [ ] I have verified that I am running the latest version of the COMET-IME
- [ ] I have searched [open](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
The crossview element definitions definition and parameter selection panel should allow for filtering of the element definitions based on the category of the element definition

### Logs

  - [ ] There are no logs regarding the issue
  - { ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- COMET version:
  - [ ] COMET-IME: 
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4/COMET Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by cozminvelciu** [comment] 2021-04-20 14:56
Already implemented via the "Filter editor" functionality that is invoked by right clicking the grid header.

Duplicate of #649.

**Closed by cozminvelciu** 2021-04-20 14:56 UTC
Labels: ?sp, CDF, feature request
