### ISSUE TITLE
Not able to create Models without Source Model (Site Administrator Role!)

### ISSUE THREAD

**Issue by DeMarlon** [RHEAGROUP/COMET-IME-Community-Edition#1015] opened 2022-02-07 10:26 UTC
### Description

Error when trying to create a new model without using another as a source model. Different error message when clicking "OK" again.
Logged in as Site Administrator Person Role

### Steps to Reproduce
1 Login as a Site Administrator Person
2 "Create Engineering Model Setup", no Source Model selected
3 OK -> first error
4 OK again -> second, different error message

### Logs

  - {x] I have attached a Screenshot 
  
### System Configuration

- COMET version:
  - [ ] COMET-IME: 9.01
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4/COMET Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 32
  - [ ] Windows OS (32/64 bit): 11, 64-bit
  - [ ] Additional information: 

<!-- Thanks for reporting the issue to COMET-IME! --
![unnamed](https://user-images.githubusercontent.com/99178407/152769869-8542d646-87e0-4e43-aaeb-1e045e182a0f.png)
![unnamed](https://
![image007](https://user-images.githubusercontent.com/99178407/152770629-7085a864-64ac-4873-873a-666a57b365bc.png)
![image006](https://user-images.githubusercontent.com/99178407/152770633-4cd5b274-e979-4f5c-907c-3ee5f4e51171.png)
user-images.githubusercontent.com/99178407/152770001-5a2a3b33-772a-4fee-a4d9-ac891e1102f3.png)
>

**Comment by samatrhea** [comment] 2022-02-14 16:39
what version of the server are you using?

**Comment by alexatrhea** [comment] 2022-04-15 07:03
We are having a hard time to reproduce this, suspect a problem with either your server installation or maybe some issues with permissions.

**Comment by alexatrhea** [comment] 2022-06-02 14:49
Closed as we cannot reproduce this.

**Closed by alexatrhea** 2022-06-02 14:49 UTC
Labels: bug, ?sp, medium
